services:
  cassandra-master:
    image: "cassandra:latest"
    container_name: "cassandra-master"
    ports:
      - 9042:9042
    networks:
      cassandra-net:
        ipv4_address: 192.168.16.2
    environment:
      - CASSANDRA_CLUSTER_NAME=bigd-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-master
    volumes:
      - ./cassandra-master:/var/lib/cassandra
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m
      start_period: 1m
      timeout: 10s
      retries: 3

  cassandra-node1:
    image: "cassandra:latest"
    container_name: "cassandra-flight-1"
    ports:
      - 9043:9042
    networks:
      cassandra-net:
        ipv4_address: 192.168.16.3
    environment:
      - CASSANDRA_CLUSTER_NAME=bigd-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-master
    depends_on:
      cassandra-master:
        condition: service_healthy
    volumes:
      - ./cassandra-node1:/var/lib/cassandra
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m
      start_period: 1m
      timeout: 10s
      retries: 3

networks:
  cassandra-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/20
          gateway: 192.168.16.1