networks:
  flight-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/20
          gateway: 192.168.16.1

services:
  flight-1:
    image: "cassandra:latest"
    container_name: "flight-1"
    ports:
      - 9042:9042
    networks:
      flight-net:
        ipv4_address: 192.168.16.2
    environment:
      - CASSANDRA_CLUSTER_NAME=flights-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=flight-datacenter
      - CASSANDRA_RACK=flight-rack1
      - CASSANDRA_SEEDS=flight-1
    volumes:
      - ./flight-node-1:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      start_period: 30s
      timeout: 10s
      retries: 3

  flight-2:
    image: "cassandra:latest"
    container_name: "flight-2"
    ports:
      - 9043:9042
    networks:
      flight-net:
        ipv4_address: 192.168.16.3
    environment:
      - CASSANDRA_CLUSTER_NAME=flights-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=flight-datacenter
      - CASSANDRA_RACK=flight-rack1
      - CASSANDRA_SEEDS=flight-1
    depends_on:
      flight-1:
        condition: service_healthy
    volumes:
      - ./flight-node-2:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      start_period: 30s
      timeout: 10s
      retries: 3
